
#---[ Dados do projeto ]---------------------------------------------------------------#

PROJECT   = icqplugin
USETHREAD = 1

SOURCES   = pwicqlib.c
MAKELIB   = $(SOURCES)
CPARMS    = -DUSEICQLIB			

ifndef OS2

#   MAKEBACKUP  = 1
   EXTRAINCL   = ../../include
   EXEPATH     = $(HOME)/public/pwicq/linux/lib

   include pwMake.gnu

endif

#---[ Diretorios ]---------------------------------------------------------------------#





